"iam": "platform settings"
# site
"iam.organization": "Tenant"
"iam.permission": "Permission"
"iam.menu-management": "Menu Setting"
"iam.role-function-management": "Role Function Management"
"iam.role-function-assignment": "Role"
"iam.member-role-global": "Role Assignment"
"iam.root-user": "Root User Setting"
"iam.valuegroup": "value Group"
"iam.lookup": "Lookup"
"iam.timedTask": "TimedTask"
"iam.message": "Message"
"iam.descriptionMaintain": "Description Maintain"
"iam.defaultRole": "Default Role"
"iam.function-permission": "Function Permission"
"iam.announce": "Platform announcement"
"iam.mailConfiguration": "Mail Configuration"
"iam.apiConfiguration": "API Key Management"
"iam.timedTask": "Timed Task Management"
"iam.platFormTimer": "Timed Task Assignment"
"iam.messageParamList": "Notification Parameters"
"iam.apiCallManagement": "API Call Details"
"iam.internalCallback": "Internal Call Interface"
"iam.callCenter": "Call Center Management"


"microservice": "Microservice"
"microservice.micro": "Microservice"
"microservice.route-management": "Route Management"
"microservice.config-management": "Config Management"
"microservice.instance-management": "Instance Management"

"workflow": "Workflow"
"workflow.automaticTransfe": "Delegate Settings"
"workflow.backLog": "To-Do"
"workflow.launchProcess": "Initiated By Me"
"workflow.takePartProcess": "With My Involvement"

"itsm": "Project Mgmt Config"
"itsm.partnerProject": "Customer"

"rentsetting": "Tenant Configuration"
# organization
"rentsetting.project": "Project"
"rentsetting.user": "Account"
"rentsetting.user2": "Account2Test"
"rentsetting.role-function-assignment": "Role"
"rentsetting.client": "Client"
"rentsetting.ldap": "LDAP"
"rentsetting.password-policy": "Password Policy"
"rentsetting.organization-management": "Organization"
"rentsetting.companyManagement": "Company Info"
"rentsetting.position-management": "Position"
"rentsetting.employee": "Member"
"rentsetting.capabilityTag": "Capability Tags"
"rentsetting.memberCapability": "Member of Capability"
"rentsetting.valuegroup": "Value of List"
"rentsetting.calendar": "Calendar"
"rentsetting.lookup": "Lookup Code"
"rentsetting.timedTask": "TimedTask"
"rentsetting.descriptionMaintain": "Description Maintain"
"rentsetting.announcement": "Announcement"
"rentsetting.approvalWorkflow": "Workflow Design"
"rentsetting.processMonitoring": "Workflow Monitor"
"rentsetting.workFlowTest": "Workflow Test"
"rentsetting.messageTemplate": "Notification Template"
"rentsetting.businessParam": "Notification Parameters"
"rentsetting.messageMonitoring": "Notification Center"
"rentsetting.accountConfiguration": "E-Mail Configuration"
"rentsetting.encodingRules": "Serial Number"
"rentsetting.partnerProject": "Partner Project"
"rentsetting.apiManagement": "API Key Management"
"rentsetting.portalManagement": "Service Portal"
"rentsetting.settingWechat": "Wechat Configuration"
"rentsetting.tenantTime": "Timer Tasks"
"rentsetting.tenantOrganization": "Tenant Management"
"rentsetting.tenantApiCallManagement": "API Call Details"
"rentsetting.accountSecurityManagement": "Account Security Management"

"portal": "Portal Configuration"
"portal.servicePortal": "Portal Configuration"

"prosetting": "Project Manage"
# project
"prosetting.proManage": "Project Manage"
"prosetting.member-role-project": "Role Assignment"

"usercenter": "Profile"
# user
"usercenter.user-info": "User Information Maintenance"
"usercenter.password": "Password Modification"
"usercenter.organization-info": "Tenant Information"
"usercenter.msgReceiveSetting": "ReceiveSetting"

"hitom": "hitom"
# hitom
"hitom.analysis": "Monitoring Analysis"
"hitom.target": "Monitoring Target"
"hitom.template": "Monitoring Template"
"hitom.role": "Role"
