"iam": "平台设置"
# site
"iam.organization": "租户管理"
"iam.permission": "权限查看"
"iam.menu-management": "菜单查看"
"iam.role-function-management": "功能权限分配"
"iam.role-function-assignment": "角色管理"
"iam.member-role-global": "平台角色分配"
"iam.root-user": "Root账户设置"
"iam.valuegroup": "值集维护"
"iam.lookup": "快码维护"
"iam.timedTask": "定时任务管理"
"iam.message": "提示信息维护"
"iam.descriptionMaintain": "描述维护"
"iam.defaultRole": "默认角色管理"
"iam.function-permission": "功能权限查看"
"iam.announce": "平台公告管理"
"iam.mailConfiguration": "邮件账户配置"
"iam.apiConfiguration": "API密钥管理"
"iam.platFormTimer": "定时任务分配"
"iam.messageParamList": "消息参数列表"
"iam.apiCallManagement": "API调用详情"
"iam.internalCallback": "内部回调接口"
"iam.callCenter": "呼叫中心管理"


"microservice": "微服务管理"
"microservice.micro": "微服务"
"microservice.route-management": "路由管理"
"microservice.config-management": "配置管理"
"microservice.instance-management": "实例管理"

"workflow": "工作流"
"workflow.launchProcess": "我发起的流程"
"workflow.takePartProcess": "我参与的流程"
"workflow.automaticTransfe": "自动转交设置"
"workflow.backLog": "我的待办审批"

"rentsetting": "租户配置"
# organization
"rentsetting.project": "项目管理"
"rentsetting.user": "账户"
"rentsetting.user2": "账户2测试"
"rentsetting.member-role-organization": "账户角色分配"
"rentsetting.role-function-assignment": "角色"
"rentsetting.client": "客户端"
"rentsetting.ldap": "LDAP"
"rentsetting.password-policy": "密码策略"
"rentsetting.organization-management": "组织"
"rentsetting.companyManagement": "公司信息"
"rentsetting.position-management": "岗位"
"rentsetting.employee": "成员"
"rentsetting.capabilityTag": "能力标签"
"rentsetting.memberCapability": "成员能力"
"rentsetting.calendar": "工作日历"
"rentsetting.valuegroup": "值集维护"
"rentsetting.lookup": "快码维护"
"rentsetting.descriptionMaintain": "描述维护"
"rentsetting.timedTask": "定时任务"
"rentsetting.announcement": "公告管理"
"rentsetting.approvalWorkflow": "流程设计与查看"
"rentsetting.processMonitoring": "流程监控"
"rentsetting.workFlowTest": "审批工作流测试"
"rentsetting.messageTemplate": "消息模板管理"
"rentsetting.businessParam": "消息参数列表"
"rentsetting.messageMonitoring": "消息监控"
"rentsetting.accountConfiguration": "邮件账户配置"
"rentsetting.encodingRules": "序列规则管理"
"rentsetting.apiManagement": "API密钥管理"
"rentsetting.portalManagement": "门户管理"
"rentsetting.settingWechat": "企业微信配置"
"rentsetting.tenantTime": "定时任务管理"
"rentsetting.tenantOrganization": "租户配置"
"rentsetting.tenantApiCallManagement": "API调用详情"
"rentsetting.accountSecurityManagement": "账户安全管理"

"portal": "门户管理"
"portal.servicePortal": "门户管理"

"itsm": "项目管理配置"
"itsm.partnerProject": "合作伙伴管理"

"prosetting": 项目设置
# project
"prosetting.proManage": "项目信息"
"prosetting.member-role-project": "项目角色分配"

"usercenter": 个人中心
# user
"usercenter.user-info": "个人信息"
"usercenter.password": "修改密码"
"usercenter.organization-info": "租户信息"
"usercenter.msgReceiveSetting": "消息接收设置"

"hitom": 监控平台
# hitom
"hitom.analysis": "监控分析"
"hitom.target": "监控目标"
"hitom.template": "监控模板"
"hitom.role": "角色管理"
